### ISSUE TITLE
the app crashed in the release mode

### ISSUE THREAD

**Issue by alleniver** [pytorch/live#11]
### Problem Area

react-native-pytorch-core (core package)

### Steps to Reproduce

Hi, the app is crashing on my phone after release mode, but it is fine in debug mode.

Env:Android 11,Moto G100
Logs:
12-09 16:27:02.492 19401 10332 E AndroidRuntime: FATAL EXCEPTION: pool-2-thread-1
12-09 16:27:02.492 19401 10332 E AndroidRuntime: Process: org.pytorch.live.example, PID: 19401
12-09 16:27:02.492 19401 10332 E AndroidRuntime: com.facebook.jni.CppException: open file failed because of errno 2 on fopen: No such file or directory, file path: /models_resnet18
12-09 16:27:02.492 19401 10332 E AndroidRuntime: Exception raised from RAIIFile at ../caffe2/serialize/file_adapter.cc:27 (most recent call first):
12-09 16:27:02.492 19401 10332 E AndroidRuntime: (no backtrace available)
12-09 16:27:02.492 19401 10332 E AndroidRuntime: 	at org.pytorch.LiteNativePeer.initHybrid(Native Method)
12-09 16:27:02.492 19401 10332 E AndroidRuntime: 	at org.pytorch.LiteNativePeer.<init>(LiteNativePeer.java:28)
12-09 16:27:02.492 19401 10332 E AndroidRuntime: 	at org.pytorch.LiteModuleLoader.load(LiteModuleLoader.java:19)
12-09 16:27:02.492 19401 10332 E AndroidRuntime: 	at org.pytorch.rn.core.ml.MobileModelModule.fetchCacheAndLoadModel(MobileModelModule.java:165)
12-09 16:27:02.492 19401 10332 E AndroidRuntime: 	at org.pytorch.rn.core.ml.MobileModelModule.lambda$preload$0$MobileModelModule(MobileModelModule.java:70)
12-09 16:27:02.492 19401 10332 E AndroidRuntime: 	at org.pytorch.rn.core.ml.-$$Lambda$MobileModelModule
12-09 16:27:02.492 19401 10332 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12-09 16:27:02.492 19401 10332 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12-09 16:27:02.492 19401 10332 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:923)

**Comment by aaronespasa** [comment]
Hi @alleniver,

Could you check if there exists a file called `resnet18.ptl` on your models/ folder?

<img width="428" alt="Screenshot 2021-12-09 at 11 00 33" src="https://user-images.githubusercontent.com/39239895/145375236-2bc4e861-d037-4889-a8bc-146cc796460d.png">

The first thing that comes to my mind is that the models were not built correctly. I'm not quite sure if this is the issue as the file/folder that the error indicates that's missing is `/models_resnet18` instead of `/models/resnet18.ptl` and you said  that the app run well on debug mode. But knowing if the models were built correctly will give some feedback to find out where the problem lies.

**Comment by liuyinglao** [comment]
@alleniver thanks for the feedback and it seems @aaronespasa  is right! May I ask 
1. did you see an error.log file under the ./models/ directory, and if you did, any content within it? 
2. what system are you in (Windows, Mac, Linux or others?)

We would have expected our post-init script to report you the error when you init the app -- you could also try rerun the [script](https://github.com/pytorch/live/blob/main/react-native-template-pytorch-live/script.js#L19-L23) to generate the missing models 

let us know how that goes!

**Comment by alleniver** [comment]
I use the win10,the /models/resnet18.ptl has exists! the packaged file has 940mb, so the model should be included. 
look the attachment please.
![image](https://user-images.githubusercontent.com/6006650/145518550-461dd5be-2dc2-4dea-8e00-ffb9199f7ef3.png)
![image](https://user-images.githubusercontent.com/6006650/145518754-2799217e-0ec6-433e-ac3d-2f62fd12edd0.png)
![image](https://user-images.githubusercontent.com/6006650/145518891-9b603d84-3b6b-4e8d-a07f-c53d7249e20e.png)

**Comment by raedle** [comment]
@alleniver, thanks for reporting this issue! I can repro on Android, and we'll be looking into a fix!

If you have a fix already, feel free to submit a PR!

**Comment by raedle** [comment]
@alleniver, @chrisklaiber could pinpoint the issue and submitted a fix with 394ba1b.

To get the changes you can do one of the following two options:

* Update the `react-native-pytorch-core` package with `yarn update react-native-pytorch-core --latest`
* Initialize a new project with `npx torchlive-cli init NewProject`

Closing the issue. Please reopen if it didn't fix the underlying issue on your end!

Thanks for reporting!

**Comment by alleniver** [comment]
good job,it's fine now! thanks.
