### ISSUE TITLE
Custom trained DETR

### ISSUE THREAD

**Issue by batrlatom** [pytorch/live#17]
### Version

latest

### Problem Area

react-native-pytorch-core (core package)

### Steps to Reproduce

Hi, I have a problem to create working live.spec.json file for my custom detr. The detr itself works fine when inferenced from python

steps to reproduce:
1. retrain detr
2. change .spec according the tutorial
section to modify ...
```
"unpack": {
    "type": "bounding_boxes",
    "key": "boundingBoxes",
    "dtype": "float",
    "probabilityThreshold": "$probabilityThreshold",
    "classes": [
      "test class"
    ]
  }
```
3. rebuild model for mobile

Problem to solve:
```Error: length=1; index=-1```

### Code example, screenshot, or link to repository

Detr was trained from this repository  ... https://github.com/woctezuma/detr.git . My custom detr has 1 class with the class indexed from 0. 

Could you please tell me what is the correct spec ?

**Comment by batrlatom** [comment]
ok, so it looks like I need to index from 1 and the the specfile looks like. Fine it works, but it would be nice to have it stated explicitly. btw., are you looking for tutorials? I could make one for retraining detr

```
"unpack": {
    "type": "bounding_boxes",
    "key": "boundingBoxes",
    "dtype": "float",
    "probabilityThreshold": "$probabilityThreshold",
    "classes": [
      "test class"
    ]
  }
```

**Comment by raedle** [comment]
Thanks for flagging this, @batrlatom!!

>are you looking for tutorials? I could make one for retraining detr

Yes, contributions to PyTorch Live are very much welcome, including new tutorials! Feel free to submit a DETR tutorial as PR!!

FYI, the classes in the example are based on the CoCo dataset, similar to what is used in [DETR panoptic in this notebook](https://colab.research.google.com/github/facebookresearch/detr/blob/colab/notebooks/DETR_panoptic.ipynb)
