### ISSUE TITLE
Template not installing with init command

### ISSUE THREAD

**Issue by Janjs** [pytorch/live#21]
### Version

v0.1.2

### Problem Area

CLI

### Steps to Reproduce

Following the tutorial, no errors on the setup, but when initializing a new project, the template doesn't get downloaded.

1. npx torchlive-cli setup-dev
2. npx torchlive-cli init MyFirstProject

error An unexpected error occurred: "https://registry.yarnpkg.com/react-native-template-react-native-template-pytorch-live: Not found".

### Expected Results

I think it should download from "https://registry.yarnpkg.com/react-native-template-pytorch-live", not "https://registry.yarnpkg.com/react-native-template-react-native-template-pytorch-live". I don't know why it tries to install from that URL.

**Comment by raedle** [comment]
Hi @Janjs, thanks for reporting the issue!

1. The `npx` (or `npm`) seems to be using the `yarn` registry. You can verify this by running the following command:

```
npm config get registry
```

which should log the default npm registry: `https://registry.npmjs.org/`.

2. Try if the following works for you:

```
npm_config_registry=https://registry.npmjs.org npx torchlive-cli init MyFirstProject
```

3. What are your versions for `node`, `npm`, and `npx`? (e.g., `node --version`)

**Comment by Janjs** [comment]
Hi @raedle thank you for the cool library and the quick response! 

1. I get `https://registry.npmjs.org/` when running `npm config get registry`.
2. Same a similar error, now with npm:
`error An unexpected error occurred: "https://registry.npmjs.org/react-native-template-react-native-template-pytorch-live: Not found".`
3. node v14.16.0, npm and npx 8.1.4

**Comment by raedle** [comment]
@Janjs, any chance `react-native` is installed globally?

1. You can check it with

```
npm list -g react-native
```

which should be `(empty)` and log something like the following:

```
/Users/$USER/.nvm/versions/node/v14.18.1/lib
└── (empty)
```

You can check all globally installed packages with the following command:

```
npm list -g --depth=0
```

Also make sure to check the globally installed packages with `yarn`:

```
yarn global list
```

If `react-native` is installed globally, remove it and try again.

2. If you tried the above and still get the `error An unexpected error occurred: "https://registry.npmjs.org/react-native-template-react-native-template-pytorch-live: Not found"`, please try adding the `--ignore-existing` flag to force npx to ignore any locally installed versions of the CLI and use the latest.

**Comment by Janjs** [comment]
Removing `react-native-cli` globally did the trick! Thank you @raedle.
