### ISSUE TITLE
add fromNativeJSRef method to ImageUtil 

### ISSUE THREAD

**Issue by Sxela** [pytorch/live#30]
### Area Select

react-native-pytorch-core (core package)

### Description

I've played around with Image2Image models, and I had to add the `fromNativeJSRef` method to `ImageUtil`, in order to wrap my inference result, as my model returned a NativeJSRef object. 
Trying to import `wrapRef` directly into my app.ts file resulted in import errors, which the typescript transpiler doesn't catch.

Maybe there is a more elegant solution, like wrapping the output directly in the MobileModelModule

**Comment by raedle** [comment]
Thanks for submitting PR #31, @Sxela. We've merged it, so I am closing this issue
