### ISSUE TITLE
Error: Unable to resolve module ../models/mobilenet_v3_small.ptl from /Users/ziyuanzhou/Desktop/signdectection/signdetection/src/screens/CameraScreenTest.js: 

### ISSUE THREAD

**Issue by JohnZcp** [pytorch/live#35]
### Version

0.1.2

### Problem Area

react-native-pytorch-core (core package)

### Steps to Reproduce

I followed the tutorial of preparing custom model, and received this error message while executing. The full message is like this:
Error: Unable to resolve module ../models/mobilenet_v3_small.ptl from /Users/ziyuanzhou/Desktop/signdectection/signdetection/src/screens/CameraScreenTest.js: 

None of these files exist:
  * src/models/mobilenet_v3_small.ptl(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)
  * src/models/mobilenet_v3_small.ptl/index(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)
  10 |
  11 | export default class CameraScreenTest extends Component{
> 12 |     model = require('../models/mobilenet_v3_small.ptl');
     |                      ^
  13 |     constructor(props){
  14 |         super(props);
  15 |         this.state = {
    at ModuleResolver.resolveDependency (/Users/ziyuanzhou/Desktop/signdectection/signdetection/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:107:15)
    at DependencyGraph.resolveDependency (/Users/ziyuanzhou/Desktop/signdectection/signdetection/node_modules/metro/src/node-haste/DependencyGraph.js:288:43)
    at Object.resolve (/Users/ziyuanzhou/Desktop/signdectection/signdetection/node_modules/metro/src/lib/transformHelpers.js:129:24)
    at resolve (/Users/ziyuanzhou/Desktop/signdectection/signdetection/node_modules/metro/src/DeltaBundler/traverseDependencies.js:396:33)
    at /Users/ziyuanzhou/Desktop/signdectection/signdetection/node_modules/metro/src/DeltaBundler/traverseDependencies.js:412:26
    at Array.reduce (<anonymous>)
    at resolveDependencies (/Users/ziyuanzhou/Desktop/signdectection/signdetection/node_modules/metro/src/DeltaBundler/traverseDependencies.js:411:33)
    at processModule (/Users/ziyuanzhou/Desktop/signdectection/signdetection/node_modules/metro/src/DeltaBundler/traverseDependencies.js:140:31)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async addDependency (/Users/ziyuanzhou/Desktop/signdectection/signdetection/node_modules/metro/src/DeltaBundler/traverseDependencies.js:230:18)

I tried to solve the this problem by adding the encoding option in make_model.py.
spec = Path("live.spec.json").read_text(encoding= "UTF-8")
But it didn't help me solve the problem.

**Comment by chrisklaiber** [comment]
Hi @JohnZcp - I'd first ensure the model file exists and is non-zero, and second that the relative `require()` path is correct. These are the two things that usually trip me up here.

Given that you're loading `require('../models/mobilenet_v3_small.ptl');` from within `/Users/ziyuanzhou/Desktop/signdectection/signdetection/src/screens/CameraScreenTest.js` I would expect it to resolve to `/Users/ziyuanzhou/Desktop/signdectection/signdetection/src/models/mobilenet_v3_small.ptl` and so:

  `ls -lh /Users/ziyuanzhou/Desktop/signdectection/signdetection/src/models/mobilenet_v3_small.ptl`

My guess is that you need another `../` in the relative `require()` path, since in the default project template, `models/` is at the same level as `src/`.

**Comment by JohnZcp** [comment]
models/ and screens/ are at the same level, they are in the src/. I tried to enter the path layer by layer, and it seems like my project just doesn't recognize this .ptl type file. 
![Screen Shot 2022-01-19 at 10 21 53 PM](https://user-images.githubusercontent.com/91770064/150284924-c2063ad4-cf47-490d-b72f-b0d6c585c77e.png)

**Comment by chrisklaiber** [comment]
I don't know what backs the autocomplete in your editor, but the asset loading is handled by Metro, and that is driven by the `metro.config.js` at the project root. To support the model files, the `.ptl` extension is added to `resolver.assetExts`.

From your error message, it almost seems like Metro is trying a regex (for the given extensions) and that `.ptl` is not present. I don't know why that would be.

Did the default project template work for you? At what point did model loading break?

Hmm, looking at the Metro documentation, I see there is `assetExts` as well as `sourceExts`: https://facebook.github.io/metro/docs/configuration/#resolver-options

I wonder if `sourceExts` is used for files below the `src/` directory, and `assetExts` elsewhere. Can you try moving `models/` up a level to be a peer to `src/`?

**Comment by JohnZcp** [comment]
Thanks for your help. I just figure out the problem. All I need is to do is adding the .ptl extension in sourceExts in metro.config.js, and be sure the model file is placed under src/ .

**Comment by chrisklaiber** [comment]
I'm glad to hear that you found a solution, @JohnZcp!

One more thing you might want to check is to ensure that this works in the release build. Metro handles file loading differently in dev mode and release mode, and it may have an impact on your approach here.

For example, if you normally build in dev mode with `yarn android`, try out release mode with `yarn android --variant=release`.
