### ISSUE TITLE
Image unwrap issue leading to Pytorch Live demo not working on iPad Pro

### ISSUE THREAD

**Issue by OptimusLime** [pytorch/live#43]
### Version

main

### Problem Area

react-native-pytorch-core (core package)

### Steps to Reproduce

1. Deploy demo to iPad. 
2. Run any example with images (for example: run Photo Example, and click on any image like Panda). 

React native will say "unhandled exception."

### Expected Results

Unwrap should not cause any issues for iPad version. 

### Code example, screenshot, or link to repository

Tracked down the failure to: 
guard let image = castedImage else { throw ImageModuleError.castingObject }
@ https://github.com/pytorch/live/blob/2282cd52946f9133551e152200cd06202be54653/react-native-pytorch-core/ios/Image/ImageModule.swift#L126

EDIT: I am happy to do the heavy lifting debugging on my end since I have an iPad Pro accessible, though I am unfamiliar with React Native + pytorch stack. Any clues will be helpful.

**Comment by OptimusLime** [comment]
The stack dump when the issue occurs: 

`0x0000000103e6b04c $s25react_native_pytorch_core21TensorFromImagePackerC4pack9modelSpec6params13packerContextSo9PTMIValueCSg10SwiftyJSON0Q0V_So12NSDictionaryCAA0hN0CtKF + 2688
1   plive_demo
0x0000000103e6c0b0 $s25react_native_pytorch_core21TensorFromImagePackerCAA0H0A2aDP4pack9modelSpec6params13packerContextSo9PTMIValueCSg10SwiftyJSON0Q0V_So12NSDictionaryCAA0hN0CtKFTW + 32
2   plive_demo
0x0000000103e646bc $s25react_native_pytorch_core14PackerRegistryC4pack9modelSpec6params13packerContextSo9PTMIValueCSg10SwiftyJSON0O0V_So12NSDictionaryCAA0eL0CtKFZ + 684
3   plive_demo
0x0000000103e1b4ac $s25react_native_pytorch_core16BaseIValuePackerC4pack6params13packerContextSo9PTMIValueCSgSo12NSDictionaryC_AA0gK0CtKF + 212
4   plive_demo
0x0000000103e1bfb4 $s25react_native_pytorch_core16BaseIValuePackerCAA07IIValueG0A2aDP4pack6params13packerContextSo9PTMIValueCSgSo12NSDictionaryC_AA0gL0CtKFTW + 32
5   plive_demo
0x0000000103e5e1b8 $s25react_native_pytorch_core17MobileModelModuleC7execute_6params8resolver8rejecterySo8NSStringC_So12NSDictionaryCyypSgcySSSg_AMs5Error_pSgtctF + 776
6   plive_demo
0x0000000103e5f5f8 $s25react_native_pytorch_core17MobileModelModuleC7execute_6params8resolver8rejecterySo8NSStringC_So12NSDictionaryCyypSgcySSSg_AMs5Error_pSgtctFTo + 236
7   CoreFoundation
0x000000019b37f8f4 727F2644-EB4E-3D57-BC2E-E6803BA92366 + 1222900
8   CoreFoundation
0x000000019b256df8 727F2644-EB4E-3D57-BC2E-E6803BA92366 + 7672
9   CoreFoundation
0x000000019b2573cc 727F2644-EB4E-3D57-BC2E-E6803BA92366 + 9164
10  plive_demo
0x0000000103a1ebf0 -[RCTModuleMethod invokeWithBridge:module:arguments:] + 1696
11  plive_demo
0x0000000103a22178 _ZN8facebook5reactL11invokeInnerEP9RCTBridgeP13RCTModuleDatajRKN5folly7dynamicEiN12_GLOBAL__N_117SchedulingContextE + 1088
12  plive_demo
0x0000000103a21b78 _ZZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEiENK3$_0clEv + 128
13  plive_demo
0x0000000103a21aec ___ZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEi_block_invoke + 28
14  libdispatch.dylib
0x0000000107fffbcc _dispatch_call_block_and_release + 32
15  libdispatch.dylib
0x00000001080016c0 _dispatch_client_callout + 20
16  libdispatch.dylib
0x0000000108009354 _dispatch_lane_serial_drain + 736
17  libdispatch.dylib
0x000000010800a0c0 _dispatch_lane_invoke + 448
18  libdispatch.dylib
0x0000000108016644 _dispatch_workloop_worker_thread + 1520
19  libsystem_pthread.dylib
0x00000001e60e9814 _pthread_wqthread + 276
20  libsystem_pthread.dylib
0x00000001e60f076c start_wqthread + 8`

**Comment by raedle** [comment]
Thanks for reaching out, @OptimusLime!

I tested PyTorch Live v0.1.3 on an iPad Pro (12.9-inch) with iOS 14.6. Both debug and release work.

Thanks for offering to debug. Let me put together instructions. Alternatively, we could also do a VC on the PyTorch Live Discord, and we debug together. Let me know what works best for you :)

![IMG_1768](https://user-images.githubusercontent.com/489051/153548783-e125ccff-0115-4e76-aad6-2ae33f74b602.png)
![IMG_1770](https://user-images.githubusercontent.com/489051/153548789-3120a0a2-6f0f-4e61-9066-95e4404082d4.png)

**Comment by liuyinglao** [comment]
Hi @OptimusLime, thanks for providing the report! I couldn't tell what's going wrong from the error message -- but I guess this could be Xcode version issue -- may I ask what is the Xcode version on your dev machine? Thanks!

**Comment by OptimusLime** [comment]
@liuyinglao Xcode 13.2.1 which I believe is the latest as of writing this comment (I'm on OSX Monterey 12.2).  

The solution, as I described in the Slack chat was to update the software on my iPad to the latest. 

I cannot debug this anymore since the iPad software was updated and the examples run, so I think it's fine to close this for now.

**Comment by raedle** [comment]
From the `#pytorch-live` channel in the PyTorch Slack:

>updating the ipad pro to latest software (15.3.1) worked

Closing this task. Please reopen if anyone has similar issues!
