### ISSUE TITLE
Is initial maxIndex = -1 in BoundingBoxesUnpacker.swift right? then, I'd like to know the reason.

### ISSUE THREAD

**Issue by SomaKishimoto** [pytorch/live#48]
### Version

0.1.3, and also latest commits

### Problem Area

react-native-pytorch-core (core package)

### Steps to Reproduce

 1. create object detection model .ptl file
 2. put the model file at src/app/models/<ptl> and input the ModelInfo in models/index.tsx 
 3. build and run the project
 4. Fatal error: Index out of range happens

I'm enjoying to do real-time object detection on ios device because of great PyTorch live that you've been making.
I'm a beginner at Swift, so I don't know what maxIndex value= -1 indicates.
After changed maxIndex value -1 ⇨ 0, this error never happen.
So, I thought the value = 0 is right one.

Could you tell me whether the maxIndex value = -1 is correct and  then the reason  Maxindex = -1 is set, thanks in advance.

### Expected Results

"Fatal error: Index out of range" doesn't happen

### Code example, screenshot, or link to repository
<img width="987" alt="screenshot_maxindex_cause_indexerror" src="https://user-images.githubusercontent.com/93568796/155848537-13eb0037-1884-4786-b422-bdf74d8f0f0a.png">

**Comment by liuyinglao** [comment]
@SomaKishimoto good catch! This is definitely a bug. I will fix it and thanks for reporting!

**Comment by liuyinglao** [comment]
@SomaKishimoto Fix is pushed and I will close the issue for now. Feel free to reopen or create new one if you are seeing other issue!
