### ISSUE TITLE
react-native-pytorch-core:externalNativeBuildDebug failed on android build above React-Native 66

### ISSUE THREAD

**Issue by SomaKishimoto** [pytorch/live#50]
### Version

0.1.3

### Problem Area

react-native-pytorch-core (core package)

### Steps to Reproduce

1. `npx react-native init AwesomeTSProject --template react-native-template-typescript`
`cd AwesomeTSProject`
`yarn add react-native-pytorch-core`

2. [follow tutorial](https://pytorch.org/live/docs/tutorials/add-package/#additional-steps-on-android)

3. `cd android && ./gradlew assembleDebug`

I attached the patch file for CMakeLists.txt, pls use that for android build above RN66.
**BUT** then, we can't build on android under RN65. 
So, please make condition branch like [this](https://github.com/mrousavy/react-native-vision-camera/blob/main/android/CMakeLists.txt) for the users 

### Expected Results

BUILD SUCCESSFUL

but 
```
> Task :react-native-pytorch-core:externalNativeBuildDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-pytorch-core:externalNativeBuildDebug'.
> Build command failed.
```

### Code example, screenshot, or link to repository

there is same issue [here](https://github.com/mrousavy/react-native-vision-camera/issues/614), and already closed.

patch : [react-native-pytorch-core+0.1.3.patch.zip](https://github.com/pytorch/live/files/8249872/react-native-pytorch-core%2B0.1.3.patch.zip)

**Comment by liuyinglao** [comment]
@SomaKishimoto we have pushed a fix for the RN 0.64+ and please let us know if you have other questions/comments!
