### ISSUE TITLE
For pyrorch live react live, how does it work? Does it use torch script or ONNX?

### ISSUE THREAD

**Issue by JonathanSum** [pytorch/live#54]
### Tutorial Select

Server Model

### Feedback

Thank you for answering.
I am planning to use a custom model, such as a model that is created by me or others. Is it possible?

Besides the question, I guess the tutorial should explain more about that.

**Comment by raedle** [comment]
@JonathanSum, PyTorch Live uses the PyTorch Mobile runtime and can run TorchScript models (assuming the model uses operators available in the standard PyTorch Mobile runtime).

The documentation has a [tutorial for how to prepare a custom model](https://pytorch.org/live/docs/tutorials/prepare-custom-model/). It requires adding a "live spec" JSON to the model's extra files.

FWIW, there will be an additional and more flexible way to integrate a custom model that is much closer to how model integration works in PyTorch Python. Let us know if you are interested in testing the new approach!
