### ISSUE TITLE
ImageUtil.toFile always return null

### ISSUE THREAD

**Issue by JohnZcp** [pytorch/live#60]
### Version

0.0.0-04292022-1206-56d9e1d56

### Problem Area

react-native-pytorch-core (core package)

### Steps to Reproduce

I am trying to save the image to the file and save in the photo library, but the result from ImageUtil.toFile is null. Here is the output from the ImageUtil.toFile:{"_U": 0, "_V": 0, "_W": null, "_X": null}. 

### Code example, screenshot, or link to repository

const handleImage = async(image) =>{
        try{
            if(distanceTravelled >= 1 && isStart){
                const results = await detectObjects(model, image);
                let frame = [];
                console.log("Frame " + count + ":");
                for(let i=0;i<results.length;i++){
                    const result = results[i];
                    const left = Math.round(result.bounding_box[0]/2.5);
                    const top = Math.round(result.bounding_box[1]/2.5);
                    const right = Math.round(result.bounding_box[2]/2.5);
                    const bottom = Math.round(result.bounding_box[3]/2.5);
                    console.log(left+"----"+top+"----"+right+"----"+bottom);
                    const boundingbox = [left, top, right, bottom];
                    frame.push(boundingbox);
                }
                boundingbox_array.push(frame);
                let path = ImageUtil.toFile(image);
                console.log(path);
                frame_array.push(path._W);
                count+=1;
                SetDistanceTravelled(0.0);
            }
            image.release();
        }catch(e){
            console.log(e);
        }
        
    };

**Comment by Gernii** [comment]
@JohnZcp this is an async function, it'll return Promise<string>, so u have to await that function. Btw, you need to read the document more carefully.

![image](https://user-images.githubusercontent.com/54741529/168870675-c2e21659-ad1f-49ca-97d5-afec59859227.png)

**Comment by clarksandholtz** [comment]
Seems this is resolved. Closing.
