### ISSUE TITLE
react-native-pytorch-core build failed on iOs simulator

### ISSUE THREAD

**Issue by bergkamp** [pytorch/live#61]
### Version

0.1.3

### Problem Area

react-native-pytorch-core (core package)

### Steps to Reproduce

M1 Pro
follow https://pytorch.org/live/docs/tutorials/add-package/
When I use yarn ios, got this error
> In .../Pods/LibTorch-Lite/install/lib/libtorch.a(empty.cpp.o), building for iOS Simulator, but linking in object file built for iOS, file '.../ios/Pods/LibTorch-Lite/install/lib/libtorch.a' for architecture arm64

but I can run it on my iPhone 13 with Xcode

### Expected Results

package.json

 ```
{
  "name": "pytrn2",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "react": "17.0.2",
    "react-native": "0.68.2",
    "react-native-pytorch-core": "^0.1.3"
  },
  "devDependencies": {
    "@babel/core": "^7.18.0",
    "@babel/runtime": "^7.18.0",
    "@react-native-community/eslint-config": "^3.0.2",
    "babel-jest": "^28.1.0",
    "eslint": "^8.16.0",
    "jest": "^28.1.0",
    "metro-react-native-babel-preset": "^0.70.3",
    "react-test-renderer": "17.0.2"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

**Comment by Gernii** [comment]
@bergkamp v0.1.3 only work with v0.65, if u want to work in react-native  v0.66+, you can check #57, maybe ít'll  help

**Comment by bergkamp** [comment]
Thanks @Gernii 
I had  downgrade react-native to v0.65,  unfortunately that the problem was not solved.

**Comment by raedle** [comment]
@bergkamp on machine architecture and OS are you seeing this error? (e.g., Intel Mac or Apple Silicon)

Can you try the `react-native-pytorch-core` version `0.2.0-rc.0`?

**Comment by bergkamp** [comment]
@raedle I used Mac with M1 Pro
I tried again and the problem is gone, My device and environment have not changed. 
Thanks
