### ISSUE TITLE
including Libtorchvision for using torchvision.ops.nms on mobile

### ISSUE THREAD

**Issue by SomaKishimoto** [pytorch/live#64]
### Area Select

react-native-pytorch-core (core package)

### Description

For use a model with torchvision.ops.nms on ios, describing pod'LibTorchvision' in Podfile is needed, though I'm not sure about android.
If the model becomes available on mobile, the range of use would expand.

**Comment by raedle** [comment]
@SomaKishimoto, thanks for reaching out! Would you be up for submitting a PR?

**Comment by SomaKishimoto** [comment]
@raedle 
I thought I should include it in our own applications, not in the pytorch / live library.
'LibTorchvision' is only needed when using a ptl model with torchvision.ops.nms and it's enough in applications.
Installing such unnecessary features only makes the library heavier.

Although I opened this issue, please allow me to withdraw it.

**Comment by SomaKishimoto** [comment]
closed

**Comment by SomaKishimoto** [comment]
closed
