### ISSUE TITLE
torchlive setup-dev stucks

### ISSUE THREAD

**Issue by Skyy93** [pytorch/live#65]
### Version

0.1.3

### Problem Area

CLI

### Steps to Reproduce

1. try to install on Mac M1 with npx torchlive-cli setup-dev
2. runs till Android SDK Manager
3. stucks there and loads forever (I have agreed to the license agreement)

### Expected Results

Installation runs further than the SDK manager

**Comment by raedle** [comment]
Hi @Skyy93, the `setup-dev` command is not working on Apple Silicon devices. The current solution to unblock is to follow the environment setup instructions on the React Native docs (see below).

>The PyTorch Live CLI currently does not support the Apple M1 chipset. However, there are instructions by the community for how to [install React Native on an Apple M1 without Rosetta](https://medium.com/@davidjasonharding/developing-a-react-native-app-on-an-m1-mac-without-rosetta-29fcc7314d70).

This is a known issue, unfortunately. The React Native docs provide guidance for Mac M1 users:

https://reactnative.dev/docs/environment-setup

<img width="1214" alt="image" src="https://user-images.githubusercontent.com/489051/173396080-e2b14ca1-6139-4e49-9862-3f78577a787d.png">
