### ISSUE TITLE
react-native-pytorch-core build failed on Android

### ISSUE THREAD

**Issue by SomaKishimoto** [pytorch/live#66]
### Version

v0.2.0-rc.1

### Problem Area

react-native-pytorch-core (core package)

### Steps to Reproduce

1. make RN clean project
2. [follow tutorial](https://github.com/pytorch/live/issues/50#:~:text=native%2Dpytorch%2Dcore-,follow%20tutorial,-cd%20android%20%26%26%20./gradlew) and build
3. get this error
```
> Configure project :app
Unable to detect AGP versions for included builds. All projects in the build should use the same AGP version. Class name for the included build object: org.gradle.composite.internal.DefaultIncludedBuild$IncludedBuildImpl_Decorated.

> Task :react-native-pytorch-core:configureCMakeDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-pytorch-core:configureCMakeDebug'.
> C/C++: /<WorkSpace>/AwesomeTSProject/node_modules/react-native-pytorch-core/android/CMakeLists.txt debug|armeabi-v7a : CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
  Please set them or make sure they are set and tested correctly in the CMake files:
  FBJNI_LIBRARY
      linked by target "torchlive" in directory /<WorkSpace>/AwesomeTSProject/node_modules/react-native-pytorch-core/android
  JSI_LIB
      linked by target "torchlive" in directory /<WorkSpace>/AwesomeTSProject/node_modules/react-native-pytorch-core/android
  PYTORCH_LIBRARY
      linked by target "torchlive" in directory /<WorkSpace>/AwesomeTSProject/node_modules/react-native-pytorch-core/android
  REACT_NATIVE_JNI_LIB
      linked by target "torchlive" in directory /<WorkSpace>/AwesomeTSProject/node_modules/react-native-pytorch-core/android
  REACT_NATIVE_UTILS_LIB
      linked by target "torchlive" in directory /<WorkSpace>/AwesomeTSProject/node_modules/react-native-pytorch-core/android

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.3.3/userguide/command_line_interface.html#sec:command_line_warnings
```

Is there anything that I need to do？

### Expected Results

BUILD SUCCESSFUL

**Comment by liuyinglao** [comment]
Hi @SomaKishimoto Sorry for the late reply. We are working on a fix. This seems to be a issue when the app is using react-native 0.68+ (pls correct me if I am wrong) -- to unblock you at this moment, you may replace the line https://github.com/pytorch/live/blob/main/react-native-pytorch-core/android/build.gradle#L201 with 

```
if (task.name.contains('configureCMake')) {
```
after install the package

Please let us know if you see other issue, thanks!

**Comment by raedle** [comment]
@SomaKishimoto, the latest nightly has support for React Native 0.68. A fix has been added in commit [fix RN0.68 can't build with react-native-pytorch-core](https://github.com/pytorch/live/commit/2cf281fea6fca9e2615b46045a3b13fb08eb93c5), which is currently only available in the nightly version.

More information is in the docs ["Add Package to Existing App"](https://pytorch.org/live/docs/next/tutorials/add-package/).

Can you let us know if this unblocks you?

We are also looking into supporting RN 0.69

**Comment by SomaKishimoto** [comment]
@raedle , Sorry for late reply. I confirmed your fix works correctly. Thanks!

**Comment by raedle** [comment]
No worries, and thanks for the response, @SomaKishimoto.

I'm going to close the issue
