### ISSUE TITLE
when react-native new architecture support(0.68 or 0.69)? 

### ISSUE THREAD

**Issue by alleniver** [pytorch/live#68]
### Area Select

react-native-pytorch-core (core package)

### Description

When will react-native new architecture be supported?

**Comment by liuyinglao** [comment]
Hi @alleniver, the ["next" version](https://www.npmjs.com/package/react-native-pytorch-core) (0.2.0.rc-3)  should support up to RN 0.67 for both Android and iOS, and RN0.68+ should also be supported on iOS. 

we are working on a fix to support RN0.68+ on Android, hopefully we can have it in the ["nightly" version](https://www.npmjs.com/package/react-native-pytorch-core) by the end of next week

**Comment by raedle** [comment]
@alleniver, the latest nightly has support for React Native `0.68`. A fix has been added in commit [fix RN0.68 can't build with react-native-pytorch-core](https://github.com/pytorch/live/commit/2cf281fea6fca9e2615b46045a3b13fb08eb93c5), which is currently only available in the nightly version.

We are also looking into supporting RN `0.69`
